In [1]:
import os
import numpy as np
import mne
import sklearn
import matplotlib.pyplot as plt
import pywt
from collections import Counter

from sklearn import svm
from sklearn.model_selection import train_test_split

from AudioOnsetUtils import *

RAW_EOG_CHANNELS = [u'EXG1', u'EXG2', u'EXG3', u'EXG4']
MASTOID_CHANNELS = [u'EXG5', u'EXG6']

In [2]:
## This cell gets filtered data so we can open ICA for Participant PNUM

def get_participant_filtered_data(PNUM):
    data_raw_file = os.path.join('raw_data', 'P' + PNUM + '-raw.fif')
    raw = mne.io.read_raw_fif(data_raw_file)

    # remove mastoid channels if present 
    if MASTOID_CHANNELS[0] in raw.ch_names:
        mne.io.set_eeg_reference(raw.load_data(), MASTOID_CHANNELS, copy=False) # inplace
        raw.drop_channels(MASTOID_CHANNELS)

    # Drop bad channels - in place on raw
    for bad_channel in raw.info['bads']:
        raw.drop_channels(bad_channel)
#         print("dropped: " + bad_channel)

    eeg_picks = mne.pick_types(raw.info, meg=False, eeg=True, eog=False, stim=False, exclude=[])

    # bandpass filter - keeping a frequency range between 0.5 (high pass filter) and 30 Hz (low pass filter)
    filtered_data = raw.load_data().filter(0.5, 30, picks=eeg_picks)
    
    return filtered_data

In [3]:
## This cell opens the ICA file for Participant PNUM

def get_ica_data_from_file(filtered_data, PNUM):
    ica = mne.preprocessing.read_ica('ica_data/P' + PNUM + '-ica.fif')

    # apply the transformation
    postica_data = ica.apply(filtered_data, exclude=ica.exclude)
    return postica_data

In [4]:
## Original code from https://github.com/sstober/openmiir-rl-2016/blob/master/openmiir/events.py#L21 and adapted 
KEYSTROKE_BASE_ID = 2000
TIME_INDEX = 0
ID_INDEX = 1

# returns two things, a True if Not Noise boolean and a tuple with three elements:
# 0- this is lyrical (0-2) <- YLABEL
# 1- start time (onsettime + cue duration if condition 1/2, else just onsettime)
# 2- end time (starttime + duration of song without cue)
def get_event_data(event_times_ids, events_index, music_version):
    event_id = event_times_ids[events_index[0]][ID_INDEX]

    if event_id < 1000:
        """
        Event Ids < 1000 are trial labels
        with the last digit indicating the condition
                1 : 'perception',
                2 : 'cued imag',
                3 : 'imag fix cross',
                4 : 'imagination',
        and the remaining digits referring to the stimulus id.
        """
        stimulus_id, condition = decode_event_id(event_id)
        
        stimulus_info = get_vers_stim_dict(music_version)[stimulus_id]
        cue_length = stimulus_info['cue_length']
        song_length = stimulus_info['song_length']
        
        events_index[0] += 1
        
        #print(get_id_to_song_name(stimulus_id))
        
        # get time of audio onset for this stimulus
        while event_times_ids[events_index[0]][ID_INDEX] != 1000:
            #print("Expected an audio onset event but got {}".format(event_times_ids[events_index[0]]))
            events_index[0] += 1
            
        audio_onset_time = event_times_ids[events_index[0]][TIME_INDEX]
        start_time = (audio_onset_time + cue_length) if condition in [1,2] else audio_onset_time
        end_time = start_time + song_length
        
        # move the pointer by 1 to prep next call to get_event_data
        events_index[0] += 1
        
        return True, (stimulus_info["audio_type"], start_time, end_time)
    else:
        # move the pointer by 1 to prep next call to get_event_data
        events_index[0] += 1
        
        return {
            1111: (False, ("noise")),
            KEYSTROKE_BASE_ID: (False, 'imagination failed'),
            KEYSTROKE_BASE_ID+1: (False, 'imagination okay')
        }[event_id]
    
    
# convert event id to stimulus (song num) and condition (1-4)
def decode_event_id(event_id):
    if event_id < 1000:
        stimulus_id = event_id // 10
        condition = event_id % 10
        return stimulus_id, condition
    else:
        return event_id

In [5]:
def get_event_data_list(event_times_ids, p):
    events_data_list = []
    events_index = [0]
    music_version = get_participant_vers(p)

    while len(events_data_list) < 50:
        is_audio, event_data = get_event_data(event_times_ids, events_index, music_version)
        if is_audio:
            # ignore AudioType.NONLYRICAL_LYRICAL (songs that have lyrics but played w/o lyrics)
            if event_data[0] == AudioType.LYRICAL or event_data[0] == AudioType.NON_LYRICAL:
                events_data_list.append(event_data)
    
    return events_data_list

In [6]:
def get_channels_eeg_data(event_matrix, start_time, end_time, ch_names, postica_data):
    # for each channel
    # extract this individual event's eeg data btwn start and endtime
    sampling_freq = postica_data.info['sfreq']

    for i in range(len(ch_names)):
        start_stop_seconds = np.array([start_time, end_time])
        start_sample, stop_sample = (start_stop_seconds * sampling_freq).astype(int)
        
        # returns a tuple, see https://mne.tools/dev/auto_tutorials/raw/10_raw_overview.html
        #print(postica_data[i, start_sample:stop_sample])
        ch_selection = postica_data[i, :]
        
#         print("==================")
#         print(ch_selection)
        
        # append eeg data list to eventMatrix
        event_matrix.append(ch_selection) 

In [ ]:
## This cell prepares X_list and Y_list (data and labels)

X_list = []
Y_list = []
monster_matrix = [] # list of matrices

#for part in get_participant_list():
for part in ["01","13","14"]:
    # load ica data for participant
    filtered_data = get_participant_filtered_data(part)
    postica_data = get_ica_data_from_file(filtered_data, part)
    
    # from ica data, get stimuli events
    events = mne.find_events(postica_data)

    # creates tuples of (event_time, event_id)
    event_times_ids = [(events[:][i][0], events[:][i][2]) for i in range(len(events))]
    
    # get a list of event datas (enum, starttime, endtime)
    events_list = get_event_data_list(event_times_ids, part)
    
    # for each event in event datas
    for audio_type,start_time,end_time in events_list:
        event_matrix = [] # list of lists

        # get eeg data for all 62 channels, put into event_matrix
        eeg_ch_names = postica_data.ch_names[:62]
        get_channels_eeg_data(event_matrix, start_time, end_time, eeg_ch_names, postica_data)

        # call normalize on event_matrix
      
        # append event_matrix to monster_matrix
        monster_matrix.append(event_matrix)
#         print("EVENT")
#         print(event_matrix)
        
        # 0 for non-lyrical, 1 for lyrical
        Y_list.append(1) if audio_type == AudioType.LYRICAL else Y_list.append(0)

Opening raw data file raw_data\P01-raw.fif...
Isotrak not found
    Read a total of 1 projection items:
        Average EEG reference (1 x 64)  idle
    Range : 0 ... 2478165 =      0.000 ...  4840.166 secs
Ready.
Removing projector <Projection | Average EEG reference, active : False, n_channels : 64>
dropped: P8
dropped: P10
dropped: T8
Reading 0 ... 2478165  =      0.000 ...  4840.166 secs...
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 0.5 - 30 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 0.50
- Lower transition bandwidth: 0.50 Hz (-6 dB cutoff frequency: 0.25 Hz)
- Upper passband edge: 30.00 Hz
- Upper transition bandwidth: 7.50 Hz (-6 dB cutoff frequency: 33.75 Hz)
- Filter length: 3381 samples (6.604 sec)

Reading ica_data/P01-ica.fif ...
Isot

(array([[-1.41231304e-09, -1.66248497e-06, -3.29649942e-06, ...,
         1.53606515e-06,  7.90617124e-07, -1.41231304e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.32568807e-09, -1.56117592e-06, -3.32793663e-06, ...,
         1.55337633e-06,  8.07686539e-07, -1.32568807e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.29249670e-09, -7.76971012e-07, -1.59139682e-06, ...,
         1.00413609e-06,  5.28104891e-07, -1.29249670e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.31505188e-09, -7.67401751e-07, -1.47059433e-06, ...,
         1.21358226e-06,  6.20967392e-07, -1.31505188e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.59492027e-09

(array([[-2.34928972e-09,  7.29053232e-07,  1.48825282e-06, ...,
        -2.56366752e-06, -1.32346104e-06, -2.34928972e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.88842974e-09,  7.35842852e-07,  1.46880941e-06, ...,
        -8.11926651e-07, -4.06363553e-07, -1.88842974e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.33494998e-09,  6.79114945e-07,  1.34797928e-06, ...,
        -7.76959188e-07, -3.85799758e-07, -2.33494998e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.11339727e-09,  3.84087565e-07,  7.68682797e-07, ...,
        -5.73377787e-07, -2.86172963e-07, -2.11339727e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.05709392e-09

(array([[-1.44603711e-09,  2.04191476e-06,  3.98265569e-06, ...,
        -1.95923280e-06, -1.01326189e-06, -1.44603711e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.63382988e-09,  1.15247102e-06,  2.22560121e-06, ...,
        -7.89725274e-07, -4.03113749e-07, -1.63382988e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.54269415e-09,  5.60565595e-07,  1.10820025e-06, ...,
        -1.08501649e-06, -5.61735921e-07, -1.54269415e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.43027358e-09,  1.52541986e-06,  2.91611259e-06, ...,
         6.95847146e-07,  3.30235364e-07, -1.43027358e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.24572024e-09

(array([[ 7.39374292e-10, -8.91948340e-08, -1.00423708e-07, ...,
        -2.75743788e-06, -1.39567951e-06,  7.39374291e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.65686339e-10,  5.50545168e-07,  1.11096926e-06, ...,
         6.74623425e-07,  4.10523735e-07, -8.65686341e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.38799095e-09,  5.13260291e-07,  1.02563922e-06, ...,
        -4.71031809e-08, -2.49355510e-09, -1.38799095e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.79751506e-09,  3.72335125e-07,  7.51670832e-07, ...,
        -3.33364192e-07, -1.46194476e-07, -1.79751506e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.37848748e-09

(array([[-2.26312044e-09, -4.99790767e-07, -9.40530081e-07, ...,
        -1.81354640e-06, -9.40617243e-07, -2.26312044e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.90949641e-09,  1.37230318e-06,  2.74657208e-06, ...,
         9.34369202e-07,  4.90532626e-07, -1.90949641e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13647331e-09,  9.49290244e-07,  1.87396899e-06, ...,
        -4.18550299e-07, -2.02640942e-07, -2.13647331e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13282386e-09,  6.98243621e-07,  1.37678892e-06, ...,
         4.61287937e-06,  2.38674124e-06, -2.13282386e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.17708006e-09

(array([[-1.08816781e-09,  2.35694299e-06,  4.55982399e-06, ...,
        -3.52601833e-06, -1.83633151e-06, -1.08816781e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.44603711e-09,  2.04191476e-06,  3.98265569e-06, ...,
        -1.95923280e-06, -1.01326189e-06, -1.44603711e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.63382988e-09,  1.15247102e-06,  2.22560121e-06, ...,
        -7.89725274e-07, -4.03113749e-07, -1.63382988e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.54269415e-09,  5.60565595e-07,  1.10820025e-06, ...,
        -1.08501649e-06, -5.61735921e-07, -1.54269415e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.43027358e-09

(array([[-1.29249670e-09, -7.76971012e-07, -1.59139682e-06, ...,
         1.00413609e-06,  5.28104891e-07, -1.29249670e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.31505188e-09, -7.67401751e-07, -1.47059433e-06, ...,
         1.21358226e-06,  6.20967392e-07, -1.31505188e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.59492027e-09, -8.07923565e-08, -1.39442095e-07, ...,
        -1.32499691e-06, -6.82935327e-07, -1.59492027e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.92651292e-09,  4.28359390e-07,  8.50687285e-07, ...,
        -6.56977973e-07, -3.34800968e-07, -1.92651292e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.11402866e-09

(array([[-1.33171596e-09,  4.68060708e-07,  8.25477581e-07, ...,
        -3.86907773e-07, -1.76908481e-07, -1.33171596e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-0.01722228, -0.017233  , -0.01724081, ..., -0.00703936,
        -0.00704205, -0.00704511]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.89956124e-09,  1.11355800e-06,  2.18834200e-06, ...,
         2.02808999e-06,  1.08908798e-06, -1.89956124e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.78398201e-09,  4.75730848e-07,  9.56667242e-07, ...,
        -1.07083194e-06, -5.36050330e-07, -2.78398201e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.90913201e-09,  1.56355699e-07,  3.40

(array([[-1.59492027e-09, -8.07923565e-08, -1.39442095e-07, ...,
        -1.32499691e-06, -6.82935327e-07, -1.59492027e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.92651292e-09,  4.28359390e-07,  8.50687285e-07, ...,
        -6.56977973e-07, -3.34800968e-07, -1.92651292e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.11402866e-09,  1.38880883e-06,  2.69631838e-06, ...,
         2.04233805e-06,  1.08714944e-06, -1.11402866e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-3.71927543e-10,  1.38634384e-07,  2.92340931e-07, ...,
        -3.29121146e-06, -1.70788855e-06, -3.71927544e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[ 7.39374292e-10

(array([[-1.89956124e-09,  1.11355800e-06,  2.18834200e-06, ...,
         2.02808999e-06,  1.08908798e-06, -1.89956124e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.78398201e-09,  4.75730848e-07,  9.56667242e-07, ...,
        -1.07083194e-06, -5.36050330e-07, -2.78398201e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.90913201e-09,  1.56355699e-07,  3.40752789e-07, ...,
        -1.35003834e-06, -6.73291250e-07, -1.90913201e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.99620886e-09,  7.97643445e-07,  1.60041825e-06, ...,
        -4.51060799e-07, -2.08166986e-07, -1.99620886e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.20473136e-09

(array([[-1.11402866e-09,  1.38880883e-06,  2.69631838e-06, ...,
         2.04233805e-06,  1.08714944e-06, -1.11402866e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-3.71927543e-10,  1.38634384e-07,  2.92340931e-07, ...,
        -3.29121146e-06, -1.70788855e-06, -3.71927544e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[ 7.39374292e-10, -8.91948340e-08, -1.00423708e-07, ...,
        -2.75743788e-06, -1.39567951e-06,  7.39374291e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.65686339e-10,  5.50545168e-07,  1.11096926e-06, ...,
         6.74623425e-07,  4.10523735e-07, -8.65686341e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.38799095e-09

(array([[-1.90913201e-09,  1.56355699e-07,  3.40752789e-07, ...,
        -1.35003834e-06, -6.73291250e-07, -1.90913201e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.99620886e-09,  7.97643445e-07,  1.60041825e-06, ...,
        -4.51060799e-07, -2.08166986e-07, -1.99620886e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.20473136e-09,  1.26488859e-06,  2.48393788e-06, ...,
        -6.99055607e-08, -2.22313663e-08, -2.20473136e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.26386153e-09,  7.99127257e-07,  1.57199570e-06, ...,
        -2.24838606e-06, -1.18457415e-06, -2.26386153e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.64099233e-09

(array([[ 7.39374292e-10, -8.91948340e-08, -1.00423708e-07, ...,
        -2.75743788e-06, -1.39567951e-06,  7.39374291e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.65686339e-10,  5.50545168e-07,  1.11096926e-06, ...,
         6.74623425e-07,  4.10523735e-07, -8.65686341e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.38799095e-09,  5.13260291e-07,  1.02563922e-06, ...,
        -4.71031809e-08, -2.49355510e-09, -1.38799095e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.79751506e-09,  3.72335125e-07,  7.51670832e-07, ...,
        -3.33364192e-07, -1.46194476e-07, -1.79751506e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.37848748e-09

(array([[-2.20473136e-09,  1.26488859e-06,  2.48393788e-06, ...,
        -6.99055607e-08, -2.22313663e-08, -2.20473136e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.26386153e-09,  7.99127257e-07,  1.57199570e-06, ...,
        -2.24838606e-06, -1.18457415e-06, -2.26386153e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.64099233e-09,  5.03630171e-07,  1.03587600e-06, ...,
         1.66611208e-07,  1.00162664e-07, -2.64099233e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.45989455e-09,  3.44114532e-07,  7.32662243e-07, ...,
        -5.64183590e-08, -4.10511516e-08, -2.45989455e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.34928972e-09

       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.38799095e-09,  5.13260291e-07,  1.02563922e-06, ...,
        -4.71031809e-08, -2.49355510e-09, -1.38799095e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.79751506e-09,  3.72335125e-07,  7.51670832e-07, ...,
        -3.33364192e-07, -1.46194476e-07, -1.79751506e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.37848748e-09,  8.85441761e-07,  1.76192407e-06, ...,
        -1.50317487e-06, -7.51751997e-07, -1.37848748e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.10036711e-10,  6.25253942e-07,  1.23695721e-06, ...,
        -9.90758296e-08, -3.58836904e-08, -8.10036711e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4

(array([[-2.64099233e-09,  5.03630171e-07,  1.03587600e-06, ...,
         1.66611208e-07,  1.00162664e-07, -2.64099233e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.45989455e-09,  3.44114532e-07,  7.32662243e-07, ...,
        -5.64183590e-08, -4.10511516e-08, -2.45989455e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.34928972e-09,  7.29053232e-07,  1.48825282e-06, ...,
        -2.56366752e-06, -1.32346104e-06, -2.34928972e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.88842974e-09,  7.35842852e-07,  1.46880941e-06, ...,
        -8.11926651e-07, -4.06363553e-07, -1.88842974e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.33494998e-09

(array([[-1.37848748e-09,  8.85441761e-07,  1.76192407e-06, ...,
        -1.50317487e-06, -7.51751997e-07, -1.37848748e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.10036711e-10,  6.25253942e-07,  1.23695721e-06, ...,
        -9.90758296e-08, -3.58836904e-08, -8.10036711e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.35011346e-10,  1.43729615e-06,  2.81141730e-06, ...,
        -2.00865527e-06, -1.12499344e-06, -2.35011347e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[8.09959103e-10, 1.17049098e-06, 2.29142596e-06, ...,
        7.09679511e-07, 3.77564332e-07, 8.09959101e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-9.86596562e-11,  1.5

(array([[-2.34928972e-09,  7.29053232e-07,  1.48825282e-06, ...,
        -2.56366752e-06, -1.32346104e-06, -2.34928972e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.88842974e-09,  7.35842852e-07,  1.46880941e-06, ...,
        -8.11926651e-07, -4.06363553e-07, -1.88842974e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.33494998e-09,  6.79114945e-07,  1.34797928e-06, ...,
        -7.76959188e-07, -3.85799758e-07, -2.33494998e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.11339727e-09,  3.84087565e-07,  7.68682797e-07, ...,
        -5.73377787e-07, -2.86172963e-07, -2.11339727e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.05709392e-09

(array([[-2.35011346e-10,  1.43729615e-06,  2.81141730e-06, ...,
        -2.00865527e-06, -1.12499344e-06, -2.35011347e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[8.09959103e-10, 1.17049098e-06, 2.29142596e-06, ...,
        7.09679511e-07, 3.77564332e-07, 8.09959101e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-9.86596562e-11,  1.56767841e-06,  3.01262234e-06, ...,
        -6.12077280e-06, -3.21244399e-06, -9.86596585e-11]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-4.30651206e-10,  1.31184895e-06,  2.58702109e-06, ...,
        -4.47303845e-06, -2.26714212e-06, -4.30651204e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.06024262e-09,  1.4

(array([[-2.33494998e-09,  6.79114945e-07,  1.34797928e-06, ...,
        -7.76959188e-07, -3.85799758e-07, -2.33494998e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.11339727e-09,  3.84087565e-07,  7.68682797e-07, ...,
        -5.73377787e-07, -2.86172963e-07, -2.11339727e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.05709392e-09,  8.76410811e-07,  1.71227914e-06, ...,
        -1.53338135e-06, -7.73583300e-07, -2.05709392e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.21533552e-09,  4.20186427e-07,  8.41565220e-07, ...,
         1.55314091e-06,  8.02119184e-07, -2.21533552e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.26312044e-09

(array([[-9.86596562e-11,  1.56767841e-06,  3.01262234e-06, ...,
        -6.12077280e-06, -3.21244399e-06, -9.86596585e-11]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-4.30651206e-10,  1.31184895e-06,  2.58702109e-06, ...,
        -4.47303845e-06, -2.26714212e-06, -4.30651204e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.06024262e-09,  1.44161442e-06,  2.81951658e-06, ...,
        -2.02063653e-08,  1.41109254e-08, -1.06024263e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.29490269e-09,  1.04087864e-06,  2.04785503e-06, ...,
        -1.17379539e-06, -5.93025204e-07, -1.29490269e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.03625579e-09

(array([[-2.21533552e-09,  4.20186427e-07,  8.41565220e-07, ...,
         1.55314091e-06,  8.02119184e-07, -2.21533552e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.26312044e-09, -4.99790767e-07, -9.40530081e-07, ...,
        -1.81354640e-06, -9.40617243e-07, -2.26312044e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.90949641e-09,  1.37230318e-06,  2.74657208e-06, ...,
         9.34369202e-07,  4.90532626e-07, -1.90949641e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13647331e-09,  9.49290244e-07,  1.87396899e-06, ...,
        -4.18550299e-07, -2.02640942e-07, -2.13647331e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13282386e-09

(array([[-1.29490269e-09,  1.04087864e-06,  2.04785503e-06, ...,
        -1.17379539e-06, -5.93025204e-07, -1.29490269e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.03625579e-09,  5.00403506e-07,  1.01815203e-06, ...,
        -6.76152869e-07, -3.33057435e-07, -2.03625579e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.05778289e-09,  5.31333110e-07,  1.05379997e-06, ...,
        -1.11367623e-07, -5.38862683e-08, -2.05778289e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.78893075e-09,  1.32706252e-06,  2.60519368e-06, ...,
        -2.38763144e-06, -1.23252932e-06, -1.78893075e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.29149610e-09

       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13647331e-09,  9.49290244e-07,  1.87396899e-06, ...,
        -4.18550299e-07, -2.02640942e-07, -2.13647331e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.13282386e-09,  6.98243621e-07,  1.37678892e-06, ...,
         4.61287937e-06,  2.38674124e-06, -2.13282386e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-2.17708006e-09,  4.51261665e-07,  9.04308736e-07, ...,
         3.06326895e-08,  2.88529363e-08, -2.17708006e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.74496373e-09,  3.94580022e-07,  7.91473819e-07, ...,
        -3.74800460e-07, -1.88111060e-07, -1.74496373e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4

       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.78893075e-09,  1.32706252e-06,  2.60519368e-06, ...,
        -2.38763144e-06, -1.23252932e-06, -1.78893075e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.29149610e-09,  1.84268688e-06,  3.58136405e-06, ...,
        -1.83408645e-06, -9.40249769e-07, -1.29149610e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-8.76342144e-10,  2.92417512e-06,  5.65827649e-06, ...,
        -2.83527086e-06, -1.45205346e-06, -8.76342146e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-9.57016838e-10, -1.12891217e-07, -1.49012325e-07, ...,
        -4.91371495e-06, -2.55406615e-06, -9.57016841e-10]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4

(array([[-1.74496373e-09,  3.94580022e-07,  7.91473819e-07, ...,
        -3.74800460e-07, -1.88111060e-07, -1.74496373e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.81016623e-09,  2.77083977e-07,  5.86402138e-07, ...,
         1.74815993e-06,  8.85113988e-07, -1.81016624e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.79381426e-09, -4.97134965e-07, -9.35013076e-07, ...,
        -1.66973482e-06, -8.59048391e-07, -1.79381426e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.90329943e-09,  1.26020090e-06,  2.45887980e-06, ...,
         1.07286693e-06,  5.52990901e-07, -1.90329944e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.57589768e-09

(array([[-1.08816781e-09,  2.35694299e-06,  4.55982399e-06, ...,
        -3.52601833e-06, -1.83633151e-06, -1.08816781e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.44603711e-09,  2.04191476e-06,  3.98265569e-06, ...,
        -1.95923280e-06, -1.01326189e-06, -1.44603711e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.63382988e-09,  1.15247102e-06,  2.22560121e-06, ...,
        -7.89725274e-07, -4.03113749e-07, -1.63382988e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.54269415e-09,  5.60565595e-07,  1.10820025e-06, ...,
        -1.08501649e-06, -5.61735921e-07, -1.54269415e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.43027358e-09

(array([[-1.57589768e-09,  4.90908907e-07,  1.00657491e-06, ...,
         7.71253446e-07,  3.99497548e-07, -1.57589769e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.69215720e-09,  3.35798833e-07,  6.33379619e-07, ...,
         3.06617522e-07,  1.58669056e-07, -1.69215720e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.47177902e-09, -1.04087885e-06, -2.01031754e-06, ...,
         8.60957928e-07,  4.43952007e-07, -1.47177902e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.41231304e-09, -1.66248497e-06, -3.29649942e-06, ...,
         1.53606515e-06,  7.90617124e-07, -1.41231304e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.32568807e-09

(array([[-1.54269415e-09,  5.60565595e-07,  1.10820025e-06, ...,
        -1.08501649e-06, -5.61735921e-07, -1.54269415e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.43027358e-09,  1.52541986e-06,  2.91611259e-06, ...,
         6.95847146e-07,  3.30235364e-07, -1.43027358e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.24572024e-09,  3.68283619e-06,  7.15738292e-06, ...,
        -4.43087166e-06, -2.25357213e-06, -1.24572025e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.12985132e-09,  2.32530355e-06,  4.54515530e-06, ...,
        -4.04335622e-06, -2.07492738e-06, -1.12985132e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.33712366e-09

(array([[-1.47177902e-09, -1.04087885e-06, -2.01031754e-06, ...,
         8.60957928e-07,  4.43952007e-07, -1.47177902e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.41231304e-09, -1.66248497e-06, -3.29649942e-06, ...,
         1.53606515e-06,  7.90617124e-07, -1.41231304e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.32568807e-09, -1.56117592e-06, -3.32793663e-06, ...,
         1.55337633e-06,  8.07686539e-07, -1.32568807e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.29249670e-09, -7.76971012e-07, -1.59139682e-06, ...,
         1.00413609e-06,  5.28104891e-07, -1.29249670e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.31505188e-09

(array([[-1.24572024e-09,  3.68283619e-06,  7.15738292e-06, ...,
        -4.43087166e-06, -2.25357213e-06, -1.24572025e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.12985132e-09,  2.32530355e-06,  4.54515530e-06, ...,
        -4.04335622e-06, -2.07492738e-06, -1.12985132e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.33712366e-09,  5.75662656e-07,  1.13015653e-06, ...,
        -8.74674702e-07, -4.51280787e-07, -1.33712366e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-1.33171596e-09,  4.68060708e-07,  8.25477581e-07, ...,
        -3.86907773e-07, -1.76908481e-07, -1.33171596e-09]]), array([0.00000000e+00, 1.95312500e-03, 3.90625000e-03, ...,
       4.84016211e+03, 4.84016406e+03, 4.84016602e+03]))
(array([[-0.01722228, -0

### Feature Extraction

In [ ]:
# code adapted from https://ataspinar.com/2018/12/21/a-guide-for-using-the-wavelet-transform-in-machine-learning/

def calculate_entropy(list_values):
    counter_values = Counter(tuple(list_values)).most_common()
    probabilities = [elem[1]/len(list_values) for elem in counter_values]
    entropy=scipy.stats.entropy(probabilities)
    return entropy
 
def calculate_statistics(list_values):
    n5 = np.nanpercentile(list_values, 5)
    n25 = np.nanpercentile(list_values, 25)
    n75 = np.nanpercentile(list_values, 75)
    n95 = np.nanpercentile(list_values, 95)
    median = np.nanpercentile(list_values, 50)
    mean = np.nanmean(list_values)
    std = np.nanstd(list_values)
    var = np.nanvar(list_values)
    rms = np.nanmean(np.sqrt(list_values**2))
    return [n5, n25, n75, n95, median, mean, std, var, rms]
 
def calculate_crossings(list_values):
    num_zero_crossings = ((val_array[:-1] * val_array[1:]) < 0).sum()
    num_mean_crossings = ((val_array[:-1] * val_array[1:]) < np.nanmean(list_values)).sum()  
    return [num_zero_crossings, num_mean_crossings]
 
def get_features(list_values):
    entropy = calculate_entropy(list_values)
    crossings = calculate_crossings(list_values)
    statistics = calculate_statistics(list_values)
    return [entropy] + crossings + statistics

In [ ]:
# adapted from https://ataspinar.com/2018/12/21/a-guide-for-using-the-wavelet-transform-in-machine-learning/
WAVELET_NAME = 'db2' 

def get_dataset_features(dataset):
    feature_vectors = []
    
    for event_eeg_index in range(0, len(dataset)):
        event_features = []
        
        for channel_index in range(0, len(dataset[event_eeg_index])):
            channel_signal = dataset[event_eeg_index][channel_index]
            print(channel_signal)
            
            coeff_list = pywt.wavedec(channel_signal, WAVELET_NAME)
            #print(coeff_list)
            for coeff in coeff_list:
                #print(coeff)
                pass
                #event_features += get_features(coeff)
                
        feature_vectors.append(event_features)
        
    X = np.array(feature_vectors)
    return X

In [ ]:
print(monster_matrix)

In [ ]:
get_dataset_features(monster_matrix)

In [ ]:
# split data using (training vs testing)
# test_size: what proportion of original data is used for test set
train_data, test_data, train_lbl, test_lbl = train_test_split(X_list, Y_list, test_size=0.20, random_state=0)

In [ ]:
def calcAccuracy(predictions, y):
    # True positives, false positives, etc.
    TP_ = np.logicaland(predictions, y)
    FP = np.logical_and(predictions, np.logicalnot(y))
    TN = np.logical_and(np.logical_not(predictions), np.logicalnot(y))
    FN = np.logical_and(np.logicalnot(predictions), y)

    TP = sum(TP)
    FP = sum(FP)
    TN = sum(TN)
    FN = sum(FN_)
    
    accuracy = (TP + TN)/(TP + FP + TN + FN)
    print('Accuracy:{}'.format(accuracy))
    
    return accuracy

In [ ]:
# perform classification using SVM
clf = svm.LinearSVC()
clf.fit(train_data, train_lbl)
y_pred = clf.predict(test_data)

# compare predictions for accuracy
accuracy = calcAccuracy(y_pred, Y_list)

# future work: we could compare accuracy linearSVC and just SVC